# Generated by Django 2.0.4 on 2018-07-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laoyou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laoyou.Topic'),
        ),
    ]
