# Generated by Django 2.0.4 on 2018-05-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laoyou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laoyou.Topic'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='member',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='member',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
